export const colombiaPaths: Record<string, string> = {
    'Antioquia': '',
    'Bogotá D.C.': '',
    'Valle del Cauca': '',
    'Cundinamarca': '',
    'Atlántico': '',
    'Santander': '',
    'Bolívar': '',
    'Boyacá': '',
    'Nariño': '',
    'Tolima': '',
    'Córdoba': '',
    'Magdalena': '',
    'Cauca': '',
    'Norte de Santander': '',
    'Huila': '',
    'Meta': '',
    'Cesar': '',
    'Caldas': '',
    'Risaralda': '',
    'Quindío': '',
    'Sucre': '',
    'La Guajira': '',
    'Chocó': '',
    'Arauca': '',
    'Casanare': '',
    'Putumayo': '',
    'Caquetá': '',
    'Guaviare': '',
    'Vaupés': '',
    'Guainía': '',
    'Amazonas': '',
    'San Andrés y Providencia': '',
    'Vichada': ''
};
